name: Changelog & versions

on:
  push:
    tags:
      - v[0-9]+
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Import modules
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run Unit tests
        run: npm test
      - name: Run e2e tests
        run: npm run e2e
      - name: Save changelog 
        run: node ${{ github.workspace }}/scripts/save_changelog/main.js ${{ secrets.TOKEN_GITHUB }} ${{ github.repository }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        shell: bash

