name: Changelog & versions

on:
  push:
    tags:
      - v[0-9]+
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Import modules
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run Unit tests
        run: npm test
      - name: Run e2e tests
        run: npm run e2e
      - name: Save changelog 
        run: node ${{ github.workspace }}/scripts/save_changelog/main.js ${{ secrets.TOKEN_GITHUB }} ${{ github.repository }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        shell: bash
  gh-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # deployment step
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set Dependencies
        run: npm ci
      - name: Build Progect
        run: npm run build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
      - name: Update Issue
        run: node ${{ github.workspace }}/scripts/save_changelog/writePagesUrl.js ${{ secrets.TOKEN_GITHUB }} ${{ github.repository }} ${{ steps.deployment.outputs.page_url }}
        

